import { randomUUID } from "node:crypto";
import {
  configure,
  TextReader,
  Uint8ArrayWriter,
  ZipWriter,
} from "@zip.js/zip.js";
import type { BarcodeSymbology, LabelObject, ParsedLabel } from "@/lib/types";
import { escapeXml, xmlHeader } from "@/lib/xml";

const NLBL_PASSWORD = ",^_A5Fus&!?j='Epiq*e";

configure({ useWebWorkers: false });

export async function writeNlbl(label: ParsedLabel): Promise<Uint8Array> {
  const formatId = randomUUID();
  const solutionId = randomUUID();
  const safeName = sanitizeFileStem(label.title || "label");
  const variables = label.objects.map((object, index) => ({
    object,
    variableId: randomUUID(),
    promptOrder: 1000 + index,
  }));

  const slnx = buildSlnx({
    solutionId,
    formatId,
    name: safeName,
    variables,
  });
  const format = buildFormat({
    formatId,
    name: safeName,
    widthMm: label.widthMm,
    heightMm: label.heightMm,
    printer: label.printer,
    variables,
  });

  const zipWriter = new ZipWriter(new Uint8ArrayWriter(), {
    password: NLBL_PASSWORD,
    encryptionStrength: 3,
    useWebWorkers: false,
  });

  await zipWriter.add(`${safeName}.slnx`, new TextReader(slnx));
  await zipWriter.add(`Formats/${safeName}`, new TextReader(format));
  return zipWriter.close();
}

type VariableBinding = {
  object: LabelObject;
  variableId: string;
  promptOrder: number;
};

function buildSlnx(input: {
  solutionId: string;
  formatId: string;
  name: string;
  variables: VariableBinding[];
}): string {
  const variableXml = input.variables
    .map((binding) => variableItem(binding))
    .join("\r\n");

  return `${xmlHeader()}<EuroPlus.NiceLabel>
  <FileVersion>52</FileVersion>
  <SolutionFileVersion Type="SolutionFileVersion">
    <FileVersion>1</FileVersion>
  </SolutionFileVersion>
  <Id>${input.solutionId}</Id>
  <Name>${escapeXml(input.name)}</Name>
  <Variables>
${variableXml}
  </Variables>
  <SpecialDataSources />
  <SampleValue Type="StringContents" />
  <SolutionPrintScenarios>
    <Item Type="SolutionPrintScenario">
      <Id>${randomUUID()}</Id>
      <Name>Solution Print Scenario</Name>
      <SampleValue Type="StringContents" />
      <BatchPrinting Type="WholePrintJobBatchPrinting">
        <Id>${randomUUID()}</Id>
        <Name>Batch Printing</Name>
        <SampleValue Type="StringContents" />
        <IsEnabled>False</IsEnabled>
        <MainFormatBatchPrintingSettings Type="BatchPrintingFormatSettings">
          <IsEnabled>False</IsEnabled>
          <HeaderFormatReference Type="ExtendedFormatReference">
            <FixedReference Type="FormatReference">
              <Id>${input.formatId}</Id>
            </FixedReference>
          </HeaderFormatReference>
          <PrinterAction>0</PrinterAction>
          <EjectPage>False</EjectPage>
        </MainFormatBatchPrintingSettings>
        <PerformPrinterActionAfterLastLabel>True</PerformPrinterActionAfterLastLabel>
        <IsConditionEnabled>False</IsConditionEnabled>
        <ConditionValue Type="ExtendedDataValue" />
        <MergeName>Batch Printing</MergeName>
        <EditorHeights></EditorHeights>
      </BatchPrinting>
      <MergeName>Solution Print Scenario</MergeName>
      <EditorHeights></EditorHeights>
    </Item>
  </SolutionPrintScenarios>
  <SolutionType>1</SolutionType>
  <LicenseInfos>
    <Item Type="SolutionLicenseInfo">
      <SerialNumber>DEMO TRIAL</SerialNumber>
    </Item>
  </LicenseInfos>
  <SolutionSummary Type="SolutionSummary">
    <SolutionName>${escapeXml(input.name)}</SolutionName>
    <FormatCount>1</FormatCount>
    <HasErrors>False</HasErrors>
  </SolutionSummary>
  <MergeName>${escapeXml(input.name)}</MergeName>
  <EditorHeights></EditorHeights>
</EuroPlus.NiceLabel>
`;
}

function variableItem(binding: VariableBinding): string {
  const { object, variableId, promptOrder } = binding;
  return `    <Item Type="Variable">
      <Id>${variableId}</Id>
      <Name>${escapeXml(object.name)}</Name>
      <DefaultValue Type="StringContents">
        <StringValue>${escapeXml(object.value)}</StringValue>
        <UserValue>${escapeXml(object.value)}</UserValue>
      </DefaultValue>
      <IsSampleValueAutoGenerated>False</IsSampleValueAutoGenerated>
      <SampleValue Type="StringContents">
        <StringValue>${escapeXml(object.value)}</StringValue>
        <UserValue>${escapeXml(object.value)}</UserValue>
      </SampleValue>
      <IsMultiline>False</IsMultiline>
      <DayRolloverTime>0</DayRolloverTime>
      <PromptOrder>${promptOrder}</PromptOrder>
      <Constraints Type="DataSourceConstraints">
        <Length>0</Length>
      </Constraints>
      <MergeName>${escapeXml(object.name)}</MergeName>
      <EditorHeights></EditorHeights>
    </Item>`;
}

function buildFormat(input: {
  formatId: string;
  name: string;
  widthMm: number;
  heightMm: number;
  printer: string | null;
  variables: VariableBinding[];
}): string {
  const width = Math.round(input.widthMm * 1000);
  const height = Math.round(input.heightMm * 1000);
  const items = layoutItems(input.variables, width, height);

  return `\uFEFF${xmlHeader()}<EuroPlus.NiceLabel Type="Format">
  <Id>${input.formatId}</Id>
  <Name>${escapeXml(input.name)}</Name>
  <SampleValue Type="StringContents" />
  <BackgroundDocumentItem Type="BackgroundDocumentItem">
    <Id>${randomUUID()}</Id>
    <Name>Picture</Name>
    <Color>FFFFFFFF</Color>
    <SampleValue Type="StringContents" />
    <PrintAsGraphics>False</PrintAsGraphics>
    <Geometry Type="RectGeometry">
      <X>0</X>
      <Y>0</Y>
      <Width>${width}</Width>
      <Height>${height}</Height>
    </Geometry>
    <ZOrder>0</ZOrder>
    <Constraints Type="DataSourceConstraints">
      <Length>0</Length>
    </Constraints>
    <MergeName>Picture</MergeName>
    <EditorHeights></EditorHeights>
  </BackgroundDocumentItem>
  <Media Type="FormatMedia">
    <PaperFormat>0</PaperFormat>
    <PaperDetails Type="PaperDetails">
      <Id>0</Id>
      <Name>Custom</Name>
      <IsCustomEpsonPaper>False</IsCustomEpsonPaper>
    </PaperDetails>
    <Type>1</Type>
    <Width>${width}</Width>
    <Height>${height}</Height>
    <MediaUnit>2</MediaUnit>
    <RfidTag Type="RfidTagDefinition">
      <RfidSecurity Type="RfidTagSecurity">
        <Version>0</Version>
      </RfidSecurity>
      <FormatReference Type="FormatReference">
        <Id>${input.formatId}</Id>
      </FormatReference>
    </RfidTag>
    <EpsonMediaTypeId>0</EpsonMediaTypeId>
    <IsEpsonBorderlessPrintingEnabled>False</IsEpsonBorderlessPrintingEnabled>
  </Media>
  <PageLayout Type="SingleFormatLayout">
    <ElementWidth>${width}</ElementWidth>
    <ElementHeight>${height}</ElementHeight>
  </PageLayout>
  <DocumentDesigns>
    <DocumentDesign Type="FormatDocumentDesign">
      <Id>${randomUUID()}</Id>
      <Name>Document Design</Name>
      <SampleValue Type="StringContents" />
      <Items>
${items}
      </Items>
      <Height>${height}</Height>
      <Width>${width}</Width>
      <MergeName>Document Design</MergeName>
      <EditorHeights></EditorHeights>
    </DocumentDesign>
  </DocumentDesigns>
  <PrintScenarioCollection>
    <PrintScenarioCollection Type="PrintScenario">
      <Id>${randomUUID()}</Id>
      <Name>Print Scenario</Name>
      <SampleValue Type="StringContents" />
      <Printer Type="Printer">
        <Id>${randomUUID()}</Id>
        <Name>${escapeXml(input.printer ?? "ZDesigner")}</Name>
        <SampleValue Type="StringContents" />
        <UseDefaultSettings>True</UseDefaultSettings>
        <MergeName>Printer</MergeName>
        <EditorHeights></EditorHeights>
      </Printer>
      <MergeName>Print Scenario</MergeName>
      <EditorHeights></EditorHeights>
    </PrintScenarioCollection>
  </PrintScenarioCollection>
  <ScriptType>1</ScriptType>
  <DocumentProperties Type="DocumentProperties" />
  <MergeName>${escapeXml(input.name)}</MergeName>
  <EditorHeights></EditorHeights>
</EuroPlus.NiceLabel>
`;
}

function layoutItems(variables: VariableBinding[], width: number, height: number): string {
  const margin = Math.round(Math.min(width, height) * 0.08);
  const barcodeHeight = Math.round(height * 0.48);
  let y = margin;
  let zOrder = 1;
  const parts: string[] = [];

  for (const binding of variables) {
    const kind = binding.object.kind;
    switch (kind) {
      case "barcode": {
        parts.push(
          barcodeItem({
            binding,
            x: margin,
            y,
            width: width - margin * 2,
            height: Math.max(6000, barcodeHeight),
            zOrder,
          }),
        );
        y += barcodeHeight + Math.round(margin * 0.6);
        zOrder += 1;
        break;
      }
      case "text":
      case "prompt": {
        parts.push(
          textItem({
            binding,
            x: margin,
            y,
            zOrder,
          }),
        );
        y += Math.round(height * 0.18);
        zOrder += 1;
        break;
      }
      default: {
        const exhaustive: never = kind;
        return exhaustive;
      }
    }
  }

  return parts.join("\r\n");
}

function textItem(input: {
  binding: VariableBinding;
  x: number;
  y: number;
  zOrder: number;
}): string {
  const { object, variableId } = input.binding;
  return `        <Item Type="TextDocumentItem">
          <Id>${randomUUID()}</Id>
          <Name>${escapeXml(object.name)}</Name>
          <FontDescriptor Type="FontDescriptor">
            <Name>Arial</Name>
            <Height>8</Height>
            <Width>0</Width>
            <Color>FF000000</Color>
            <LogFontWrapper Type="LogFontWrapper">
              <Height>-67</Height>
              <Width>0</Width>
              <OutPrecision>4</OutPrecision>
              <ClipPrecision>32</ClipPrecision>
              <Quality>1</Quality>
              <PitchAndFamily>34</PitchAndFamily>
              <FaceName>Arial</FaceName>
            </LogFontWrapper>
          </FontDescriptor>
          <Color>FF000000</Color>
          <SampleValue Type="StringContents" />
          <PrintAsGraphics>False</PrintAsGraphics>
          <Geometry Type="PositionGeometry">
            <X>${input.x}</X>
            <Y>${input.y}</Y>
          </Geometry>
          <FixedContents>${escapeXml(object.value)}</FixedContents>
          <Contents Type="ExtendedDataValue">
            <FixedValue Type="StringContents">
              <StringValue>${escapeXml(object.value)}</StringValue>
            </FixedValue>
          </Contents>
          <BestFitMinimumFontSize>4</BestFitMinimumFontSize>
          <BestFitMaximumFontSize>72</BestFitMaximumFontSize>
          <ZOrder>${input.zOrder}</ZOrder>
          <Constraints Type="DataSourceConstraints">
            <Length>0</Length>
          </Constraints>
          <DataSourceReference Type="SolutionDataSourceReference">
            <Id>${variableId}</Id>
          </DataSourceReference>
          <MergeName>${escapeXml(object.name)}</MergeName>
          <EditorHeights></EditorHeights>
        </Item>`;
}

function barcodeItem(input: {
  binding: VariableBinding;
  x: number;
  y: number;
  width: number;
  height: number;
  zOrder: number;
}): string {
  const { object, variableId } = input.binding;
  const symbology = object.symbology ?? "code128";
  return `        <Item Type="BarcodeDocumentItem">
          <Id>${randomUUID()}</Id>
          <Name>${escapeXml(object.name)}</Name>
          <Color>FF000000</Color>
          <BarcodeData Type="${barcodeDataType(symbology)}">
            <HasCheckDigit>False</HasCheckDigit>
            <AutomaticCheckDigit>True</AutomaticCheckDigit>
            <HasManualEncoding>False</HasManualEncoding>
            <BaseBarWidth>250</BaseBarWidth>
            <UserBarWidth>250</UserBarWidth>
            <ModuleHeight>${input.height}</ModuleHeight>
            <UserRatio>3</UserRatio>
            <Ratio>3</Ratio>
            <HumanInterpretationPosition>1</HumanInterpretationPosition>
            <DisplayCheckDigit>False</DisplayCheckDigit>
          </BarcodeData>
          <SampleValue Type="StringContents">
            <StringValue>${escapeXml(object.value)}</StringValue>
            <UserValue>${escapeXml(object.value)}</UserValue>
          </SampleValue>
          <PrintAsGraphics>False</PrintAsGraphics>
          <Geometry Type="PositionGeometry">
            <X>${input.x}</X>
            <Y>${input.y}</Y>
          </Geometry>
          <FixedContents>${escapeXml(object.value)}</FixedContents>
          <DesiredWidth>${input.width}</DesiredWidth>
          <DesiredHeight>${input.height}</DesiredHeight>
          <ZOrder>${input.zOrder}</ZOrder>
          <Constraints Type="DataSourceConstraints">
            <Length>0</Length>
          </Constraints>
          <DataSourceReference Type="SolutionDataSourceReference">
            <Id>${variableId}</Id>
          </DataSourceReference>
          <MergeName>${escapeXml(object.name)}</MergeName>
          <EditorHeights></EditorHeights>
        </Item>`;
}

function barcodeDataType(symbology: BarcodeSymbology): string {
  switch (symbology) {
    case "code128":
      return "Code128BarcodeData";
    case "code39":
      return "Code39BarcodeData";
    case "ean13":
      return "Ean13BarcodeData";
    case "qr":
      return "QrCodeBarcodeData";
    case "datamatrix":
      return "DataMatrixBarcodeData";
    default: {
      const exhaustive: never = symbology;
      return exhaustive;
    }
  }
}

function sanitizeFileStem(value: string): string {
  const cleaned = value.replaceAll(/[^\p{L}\p{N}_-]+/gu, "_").replaceAll(/^_+|_+$/g, "");
  return cleaned.slice(0, 60) || "label";
}
